# Generated by Django 6.0.4 on 2026-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=110)),
                ('autor', models.CharField(max_length=110)),
                ('ano_publicacao', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
            ],
        ),
    ]
