# Generated by Django 6.0.4 on 2026-05-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='genero',
        ),
    ]
