# Generated by Django 6.0.4 on 2026-07-15 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_remove_obra_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Quero Ler', 'Quero Ler'), ('Lendo', 'Lendo'), ('Lidos', 'Lidos'), ('Em Pausa', 'Em Pausa')], default='Quero Ler', max_length=20)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
